### ISSUE TITLE
`vsce package` failes on NodeJS `12.13.0` but works on earlier versions

### ISSUE THREAD

**Issue by gencer** [microsoft/vscode-vsce#397]
When I run `vsce package`, it fails on latest LTS Version of NodeJS at the moment which is `12.13.0` but it works on earlier versions such as `12.12.0`

Stack trace:

```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './presets/default'
Require stack:
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\lib\index.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\index.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\out\package.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\out\main.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\out\vsce
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\lib\index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\node_modules\\markdown-it\\lib\\index.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\node_modules\\markdown-it\\index.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\out\\package.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\out\\main.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\out\\vsce'
  ]
}

```

**Comment by joaomoreno** [comment]
Looks like npm installed vsce only partially. Can you reinstall vsce? `npm i -g vsce`

**Comment by gencer** [comment]
Already tried. Many times. Only solution is to switch an older version at the moment.

**Comment by joaomoreno** [comment]
Does the following file exist on disk?

```
C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\lib\presets\default.js
```

**Comment by gencer** [comment]
No. I do not see this file in fact not the folder presets/

**Comment by joaomoreno** [comment]
So what's the version in:

```
C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\package.json
```

You might have a corrupt npm cache.

**Comment by gencer** [comment]
Hi Joao,

Sorry for late replies. I was out of city & sick in combination.

Here is content of poackage.json in `vsce/node_modules/markdown-it` folder

```
{
  "_from": "markdown-it@^8.3.1",
  "_id": "markdown-it@8.4.2",
  "_inBundle": false,
  "_integrity": "sha512-GcRz3AWTqSUphY3vsUqQSFMbgR38a4Lh3GWlHRh/7MRwz8mcu9n2IO7HOh+bXHrR9kOPDl5RNCaEsrneb+xhHQ==",
  "_location": "/vsce/markdown-it",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "markdown-it@^8.3.1",
    "name": "markdown-it",
    "escapedName": "markdown-it",
    "rawSpec": "^8.3.1",
    "saveSpec": null,
    "fetchSpec": "^8.3.1"
  },
  "_requiredBy": [
    "/vsce"
  ],
  "_resolved": "https://registry.npmjs.org/markdown-it/-/markdown-it-8.4.2.tgz",
  "_shasum": "386f98998dc15a37722aa7722084f4020bdd9b54",
  "_spec": "markdown-it@^8.3.1",
  "_where": "C:\\Program Files\\nodejs\\node_modules\\vsce",
  "bin": {
    "markdown-it": "bin/markdown-it.js"
  },
  "bugs": {
    "url": "https://github.com/markdown-it/markdown-it/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "argparse": "^1.0.7",
    "entities": "~1.1.1",
    "linkify-it": "^2.0.0",
    "mdurl": "^1.0.1",
    "uc.micro": "^1.0.5"
  },
  "deprecated": false,
  "description": "Markdown-it - modern pluggable markdown parser.",
  "devDependencies": {
    "ansi": "^0.3.0",
    "autoprefixer-stylus": "^0.11.0",
    "benchmark": "~2.1.0",
    "browserify": "*",
    "chai": "^3.4.1",
    "coveralls": "~2.11.9",
    "eslint": "^3.5.0",
    "express": "^4.14.0",
    "highlight.js": "^9.2.0",
    "istanbul": "^0.4.5",
    "jade": "~1.11.0",
    "markdown-it-abbr": "^1.0.4",
    "markdown-it-container": "^2.0.0",
    "markdown-it-deflist": "^2.0.0",
    "markdown-it-emoji": "^1.1.1",
    "markdown-it-footnote": "^3.0.1",
    "markdown-it-for-inline": "~0.1.0",
    "markdown-it-ins": "^2.0.0",
    "markdown-it-mark": "^2.0.0",
    "markdown-it-sub": "^1.0.0",
    "markdown-it-sup": "^1.0.0",
    "markdown-it-testgen": "~0.1.3",
    "mocha": "*",
    "ndoc": "^5.0.0",
    "stylus": "~0.54.2",
    "supertest": "^3.0.0",
    "uglify-js": "^3.0.18"
  },
  "files": [
    "index.js",
    "bin/",
    "lib/",
    "dist/"
  ],
  "homepage": "https://github.com/markdown-it/markdown-it#readme",
  "keywords": [
    "markdown",
    "parser",
    "commonmark",
    "markdown-it",
    "markdown-it-plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "markdown-it",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/markdown-it/markdown-it.git"
  },
  "scripts": {
    "heroku-postbuild": "npm install express",
    "test": "make test"
  },
  "version": "8.4.2"
}
```

**Comment by gencer** [comment]
## Update

I've reinstalled NVM and Node.js and everything worked this time. I suspect this was a CDN issue or something at that time.
